export const GETSTARTED = 'Get Started';
import MovieDetail from '../screens/movie/movieDetail';
export const SIGNIN = 'Sign In';
export const WATCHLIST = 'Watch List';
export const ADDNEWLIST = 'Add New List';
export const TAB = 'Tab';
export const HOME = 'Home';
export const NETHOT = 'Net & Hot';
export const SEARCH = 'Search';
export const DOWNLOADS = 'Downloads';
export const MOVIEDETAIL = 'Movie Detail';
